server.port=8080
spring.application.name=kartodromo-web
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
server.servlet.session.timeout=30m
logging.level.root=WARN
logging.level.pt.kartodromo=INFO
